### ISSUE TITLE
Question about extracting keyphrases

### ISSUE THREAD

**Issue by Taosky** [memray/seq2seq-keyphrase#11]
I want to extract keyphrases from my own data using the model. 

But I am confused with 'testing_datasets', is it direct to 'testing-data/' or direct to 'baseline-data/' ? 

Shoud I transfer my data to both testing-data and baseline-data?

Also has this [error](https://github.com/memray/seq2seq-keyphrase/issues/10)

**Comment by Taosky** [comment]
issue closed

**Comment by Taosky** [comment]
#11 issue closed

**Comment by memray** [comment]
Hi,

'baseline_data' is the one used for evaluation. 'testing-data' stores the datasets in their original formats. I process and save them in 'baseline_data' with a uniform format (two folders, 'text' and 'keyphrase'). 

It is running well on my side. Can you check out the latest version and let me know if the error occurs again?

Thanks,
Rui

**Comment by Taosky** [comment]
Thanks.
But the error still exists when I cloned the newest code, 

This is the error output.
````
Loading testing dataset INSPEC from /home/***/***/seq2seq-keyphrase/dataset/keyphrase/testing-data/IN
SPEC
inspec
Size of test data=0
/home/***/.virtualenvs/seq2seq_keyphrase/local/lib/python2.7/site-packages/numpy/lib/function_base.py:1128
: RuntimeWarning: Mean of empty slice.
````
Is there something wrong in the downloaded dataset.
````
$ ls dataset/keyphrase/testing-data/INSPEC/     
all_texts                         gold_standard_keyphrases_2_before_remove_prefix  README
all_texts (before remove prefix)  gold_standard_keyphrases_3                       test_texts
gold_standard_keyphrases_1        gold_standard_test                               train_validation_texts
gold_standard_keyphrases_2        gold_standard_train_validation

$ ls dataset/keyphrase/baseline-data/inspec/
keyphrase  text
````

**Comment by memray** [comment]
Thank you for getting back to me. It looks like loading test data is not successful, but I don't see anything wrong with the folders and files. 

Would you please debug and check if python is loading from the right place? I set the root path [here](https://github.com/memray/seq2seq-keyphrase/blob/51a1b6ea6acdf602f91ab8954349799351020425/keyphrase/config.py#L18), but it may not work for you.

**Comment by Taosky** [comment]
The root path may not be the reason.
I change the
code in `keyphrase_test_datasets.py line:218` to `if n_.endswith('.keyphrases')]` 
and code in `keyphrase_copynet.py line:579`  to `if 'return_encoding' in config and config['return_encoding']`.
It works.

But I am still not clear with what I should do to my data. Could you list special steps about it?

There are two functions in config.py. What's the difference between the two and which one should I set?

Thanks.

**Comment by memray** [comment]
Sorry, it has been too long and I forgot something. 

The function `load_testing_data_postag()` at line [181](https://github.com/memray/seq2seq-keyphrase/blob/51a1b6ea6acdf602f91ab8954349799351020425/keyphrase/dataset/keyphrase_test_dataset.py#L181) is the original loader. It loads from the 'baseline-data/' but you need to do POS-tagging on the text first. Later on, I feel it is not necessary, thus I wrote a new one 'load_testing_data()' (line [215](https://github.com/memray/seq2seq-keyphrase/blob/51a1b6ea6acdf602f91ab8954349799351020425/keyphrase/dataset/keyphrase_test_dataset.py#L215)) which loads from the original data and now it causes troubles. The way you did should work well.

In order to run your own data, you can simply replace the files in INSPEC (put texts in '/test_texts/' and groundtruth in '/gold_standard_test/') and make sure the data format is the same. You can also create a new loader in the same way of [INSPEC](https://github.com/memray/seq2seq-keyphrase/blob/51a1b6ea6acdf602f91ab8954349799351020425/keyphrase/dataset/keyphrase_test_dataset.py#L247).

**Comment by Taosky** [comment]
Looks like it's successful. But no new folder generated in `dataset/keyphrase/prediction/`.
New folder was generated when use the default inspec test text, does test text file must be at windows format?

**Comment by Taosky** [comment]
Sorry, a new problem appears.

I replaced test text with my own data(title in line 1, content in line 2), then the script finished without error output.
But theres no new folder in `dataset/keyphrase/prediction/`. Does the script depends on windows system or windows-like text format?

I try to use 3 of the origin inspec test data to test, there's also no new folder generated.

I can only guess that it's about config and text format.

**Comment by memray** [comment]
Yes, I think it is due to configs.
For [extracting keyphrases](https://github.com/memray/seq2seq-keyphrase#extracting-keyphrases), you need to set `config['do_predict'] = True`. The code for outputting predictions is [here](https://github.com/memray/seq2seq-keyphrase/blob/070ff8fc4abb51b96e4935934e70b8d92c6666f6/keyphrase/keyphrase_utils.py#L382). You can set a breakpoint to see whether this line is working or not.

**Comment by Taosky** [comment]
I found that I must set `config['do_evaluate'] = True` .

There was always an ascii error in [source_str](https://github.com/memray/seq2seq-keyphrase/blob/070ff8fc4abb51b96e4935934e70b8d92c6666f6/keyphrase/keyphrase_utils.py#L85), I replaced non-ascii characters and it finally worked.

Thank you very much~

**Comment by pidugusundeep** [comment]
@memray @Taosky 
Hey i have a couple of documents which are in text format and i would like to go ahead and test this model, can i create a folder in ```testing-data``` and place all the text files of the documents and run the ```keyphrase_test_dataset.py``` ?? and what are the other things i have to take care of ?
